# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('made_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('order', models.IntegerField()),
                ('hit', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdike.Document')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webdike.Sentence')),
            ],
        ),
    ]
