# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webdike', '0003_auto_20171110_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='parent_step',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='webdike.Step'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='step',
            name='stage',
            field=models.IntegerField(choices=[(0, 'Splitted'), (1, 'Polished'), (2, 'Connected'), (3, 'Explained')]),
        ),
    ]
