# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webdike', '0003_auto_20171110_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='sid',
        ),
        migrations.AddField(
            model_name='sentence',
            name='current_stage',
            field=models.CharField(choices=[('SP', 'Splitted'), ('PO', 'Polished'), ('CN', 'Connected'), ('EX', 'Explained')], default='1', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='sentence',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='webdike.Sentence'),
            preserve_default=False,
        ),
    ]
