# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdike', '0004_auto_20171119_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='current_stage',
        ),
    ]
