# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdike', '0005_remove_sentence_current_stage'),
        ('webdike', '0004_auto_20171123_1021'),
    ]

    operations = [
    ]
