# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webdike', '0007_auto_20171123_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webdike.Sentence'),
        ),
    ]
