# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webdike', '0010_step_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='parent_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webdike.Step'),
        ),
    ]
