# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdike', '0011_auto_20171124_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='active',
        ),
        migrations.AddField(
            model_name='step',
            name='population',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='step',
            name='stage',
            field=models.IntegerField(choices=[(0, 'Imported'), (1, 'Splitted'), (2, 'Polished'), (3, 'Connected'), (4, 'Explained')]),
        ),
    ]
