# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdike', '0012_auto_20171126_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='vote',
            field=models.IntegerField(default=1),
        ),
    ]
