# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webdike', '0012_auto_20171126_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webdike.Sentence'),
        ),
        migrations.AlterField(
            model_name='step',
            name='population',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='step',
            name='vote',
            field=models.IntegerField(default=1),
        ),
    ]
