# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdike', '0013_auto_20171126_2102'),
        ('webdike', '0013_auto_20171126_2030'),
    ]

    operations = [
    ]
