# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdike', '0014_merge_20171127_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_valid_step_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
